export type PositionTitle =  'Full Stack Developer'
 | '.Net Developer'
 | '.Net Full Stack Developer'
 | 'Web Developer'
 | 'Software Developer'
 | 'Senior Software Developer'
 | 'Senior Full Stack Developer'
 | 'Senior Developer'
 | 'Senior Engineer'
 | 'Senior Engineer & AI Systems Developer'
 | 'Senior Software Engineer'
 | 'Senior Software Engineer · .NET & Azure · AI / RAG Systems'
 | 'Senior / Full-Stack Developer (Various Roles)'
 | 'Technical Sales'
 | 'Software Engineer'
 ;
