export type PositionTitle =  'Full Stack Developer'
 | '.Net Developer'
 | '.Net Full Stack Developer'
 | 'Web Developer'
 | 'Software Developer'
 | 'Senior Software Developer'
 | 'Senior Full Stack Developer'
 | 'Senior Developer'
 | 'Senior Engineer'
 | 'Senior Engineer & AI Systems Developer'
 | 'Technical Sales'
 | 'Software Engineer'
 ;